common:
  name: common
  version: 0.1.0
  latent_size: 128
  context_size: 10

cpc:
  name: cpc
  version: 0.1.0
  lr: 0.001
  stride: 10
  window_size: 100
  seq_len: 10
  batch_size: 32
  num_epochs: 10

cox:
  name: cox
  version: 0.1.0
  lr: 0.001
  batch_size: 32
  num_epochs: 10


hydra:
  sweeper:
    params:
      common.latent_size: 16,32,64,128,256
      # common.context_size: 16,32,64,128,256
      # # CPC Configuration
      # cpc.window_size: 50,100,200
      # cpc.seq_len: 5,10,20
      # cpc.batch_size: 16,32,64,128
      # cpc.num_epochs: 10,20,50,100,200
      # cpc.lr: 0.1,0.01,0.001,0.0001

      # cox.lr: 0.1,0.01,0.001,0.0001
      # cox.batch_size: 16,32,64,128
      # cox.num_epochs: 10,20,50,100,200


